### ISSUE TITLE
Redeploy: extra variables passed to sub shell

### ISSUE THREAD

**Issue by flfernandez** [sky-uk/clusterverse#101]
Due to how Redeploy invokes the _cluster.yml_ using a sub shell, there is currently no way to pass variables to the _cluster.yml_ , so for example it could differentiate between a standard run and a redeployment run.

So my suggestion is to have an extra dictionary variable passed (_redeploy_extra_vars_) on all redeployment methods to the sub shell invoking _cluster.yml_

Example
- redeploy.yml playbook:
```
- name: Redeploy
  hosts: localhost
  connection: local
  tasks:
    - name: Run redeploy
      include_role:
        name: clusterverse/redeploy
      vars:
        mainclusteryml: "cluster.yml"
        predeleterole: "persistence-cassandra/redeploy"
        redeploy_extra_vars:
          cassandra_redeploy: True
```

- roles/clusterverse/redeploy/_scheme_addnewvm_rmdisk_rollback/tasks/redeploy_by_hosttype_by_host.yml:
https://github.com/sky-uk/clusterverse/blob/master/redeploy/_scheme_addnewvm_rmdisk_rollback/tasks/redeploy_by_hosttype_by_host.yml#L3
```
- name: "Run {{mainclusteryml}} to add {{cluster_host_redeploying.hostname}} to cluster"
  shell: "{{ (argv | join(' ')) | regex_replace('redeploy.yml', mainclusteryml) }} -e '{'redeploy_extra_vars': {{redeploy_extra_vars|default({})|to_json}}}' -e cluster_suffix={{cluster_suffix}} -e '{'cluster_hosts_target': [{{cluster_host_redeploying | to_json}}]}'"
  register: r__mainclusteryml
  no_log: True
  ignore_errors: yes
```

- roles/clusterverse/redeploy/_scheme_rmvm_keepdisk_rollback/tasks/by_hosttype_by_host.yml:
https://github.com/sky-uk/clusterverse/blob/master/redeploy/_scheme_rmvm_keepdisk_rollback/tasks/by_hosttype_by_host.yml#L26
```
- name: "by_hosttype_by_host | Run {{mainclusteryml}} to add {{host_to_redeploy.hostname}} to cluster"
  shell: "{{ (argv | join(' ')) | regex_replace('redeploy.yml', mainclusteryml) }} -e '{'redeploy_extra_vars': {{redeploy_extra_vars|default({})|to_json}}}' -e cluster_suffix={{cluster_suffix}} -e '{'cluster_hosts_target': [{{host_to_redeploy | to_json}}]}'"
  register: r__mainclusteryml
  no_log: True
  ignore_errors: yes
```

- roles/clusterverse/redeploy/_scheme_rmvm_rmdisk_only/tasks/by_hosttype_by_host.yml
https://github.com/sky-uk/clusterverse/blob/master/redeploy/_scheme_rmvm_rmdisk_only/tasks/by_hosttype_by_host.yml#L18
```
- name: "Run {{mainclusteryml}} to fix cluster"
  shell: "{{ (argv | join(' ')) | regex_replace('redeploy.yml', mainclusteryml) -e '{'redeploy_extra_vars': {{redeploy_extra_vars|default({})|to_json}}}'}}"
  register: r__mainclusteryml
  no_log: True
  ignore_errors: yes
```
