### ISSUE TITLE
Wait for SSH connectivity not working as expected

### ISSUE THREAD

**Issue by mikekrasn** [sky-uk/clusterverse#65]
The [Wait for SSH connectivity](https://github.com/sky-uk/clusterverse/blob/b9dee3b765adb211a19b7cca9a3deec6bcfe8b97/dynamic_inventory/tasks/main.yml#L18) task is not taking to the consideration `retries` and uses one defined in asible.cfg. 

Instead `wait_for_connection module` can be used. Please see the following test playbook (should be run with -vvv)
```yaml
- name: Retries check
  hosts: localhost
  connection: local
  gather_facts: false
  ignore_unreachable: true
  vars:    
    dynamic_inventory_flat:
      - inventory_ip: 192.168.100.254
      # - inventory_ip: 192.168.100.253
  tasks:
    - name: dynamic_inventory | Wait for SSH connectivity using ping
      ping:
      delegate_to: "{{ item.inventory_ip }}"
      with_items: "{{ dynamic_inventory_flat }}"
      retries: 12

    - debug:
        msg: "dummy delimeter"

    - name: dynamic_inventory | Wait for SSH connectivity using wait_for_connection
      wait_for_connection:
        timeout: 120
      delegate_to: "{{ item.inventory_ip }}"
      with_items: "{{ dynamic_inventory_flat }}"
```
