### ISSUE TITLE
Host type specific security groups

### ISSUE THREAD

**Issue by kristian-shaw** [sky-uk/clusterverse#75]
Currently with Clusterverse, I'm forced to apply the same set of security groups to all host types which can present a security flaw where ports are open on components where they don't need to be. I propose that it should be possible to set security groups per host type as well as for the whole cluster.

Here is an snippet of example config I would like to be able to use:
```
...
  secgroups_existing: []
  secgroup_new:
    - proto: tcp
      ports: [22]
      cidr_ip: 10.0.0.0/8
      rule_desc: SSH Access
    - proto: all
      group_name: ["{{ cluster_name }}-sg"]
      rule_desc: Master security group instances
  tools:
    hosttype_vars:
      master:
        vms_by_az: {a: 1}
        flavor: t3.micro
        secgroups_existing: []
        secgroup_new:
          - proto: tcp
            ports: [443]
            cidr_ip: 10.0.0.0/8
            rule_desc: Web UI Access
        auto_volumes:
          - {device_name: /dev/sdf, mountpoint: /var/lib/docker, fstype: ext4, volume_type: gp2, volume_size: 20, ephemeral: False, encrypted: False, delete_on_termination: True}
          - {device_name: /dev/sdg, mountpoint: "{{ jenkins_home_dir }}", fstype: ext4, volume_type: gp2, volume_size: 50, ephemeral: False, encrypted: False, delete_on_termination: True}
...
```
