### ISSUE TITLE
[AWS] Support for spot instances

### ISSUE THREAD

**Issue by flfernandez** [sky-uk/clusterverse#90]
The use of AWS Spot instances can offer big savings on development environments deployed in AWS.

Currently clusterverse uses Ansible EC2 module to deploy AWS instances, however it does not support Spot instance types due to how parameters are passed via cluster definitions.

The AWS EC2 module does offer support for Spot:
https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_module.html#ansible-collections-amazon-aws-ec2-module

```
# Spot instance example
- amazon.aws.ec2:
    spot_price: 0.24
    spot_wait_timeout: 600
    keypair: mykey
    group_id: sg-1dc53f72
    instance_type: m1.small
    image: ami-6e649707
    wait: yes
    vpc_subnet_id: subnet-29e63245
    assign_public_ip: yes
    spot_launch_group: report_generators
    instance_initiated_shutdown_behavior: terminate
```
